--- linux-2.4.x/Makefile	2004-02-17 20:52:16.000000000 +0800
+++ Makefile	2004-03-26 01:01:28.000000000 +0800
@@ -5,7 +5,7 @@
 
 KERNELRELEASE=$(VERSION).$(PATCHLEVEL).$(SUBLEVEL)$(EXTRAVERSION)
 
-# ARCH := armnommu
+ARCH := armnommu
 # ARCH := m68knommu
 # ARCH := h8300
 # ARCH := niosnommu
@@ -40,7 +40,7 @@
 HOSTCFLAGS	= -Wall -Wstrict-prototypes -O2 -fomit-frame-pointer
 
 # CROSS_COMPILE 	= m68k-elf-
-# CROSS_COMPILE 	= arm-elf-
+CROSS_COMPILE 	= arm-elf-
 # CROSS_COMPILE 	= h8300-elf-
 # CROSS_COMPILE 	= nios-elf-
 # CROSS_COMPILE		= e1-coff-
@@ -187,7 +187,8 @@
 
 DRIVERS-$(CONFIG_ACPI_BOOT) += drivers/acpi/acpi.o
 DRIVERS-$(CONFIG_PARPORT) += drivers/parport/driver.o
-DRIVERS-y += drivers/char/char.o \
+DRIVERS-y += drivers/serial/serial.o \
+	drivers/char/char.o \
 	drivers/block/block.o \
 	drivers/misc/misc.o \
 	drivers/net/net.o
